# Generated by Django 3.1.5 on 2021-03-19 18:03

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('student_class', models.IntegerField(blank=True, null=True)),
                ('encoding', django_mysql.models.ListCharField(models.CharField(max_length=17), max_length=2600, size=128)),
            ],
        ),
    ]
