# Generated by Django 3.1.5 on 2021-05-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
