# Generated by Django 3.2.3 on 2021-05-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20210516_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='period',
            name='time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
